### ISSUE TITLE
Not compiling in CentOS

### ISSUE THREAD

**Issue by boldmss** [samm-git/btest-opensource#7]
Hi, i am having problems compiling BTest in CentOS
Here is my output.

[root@localhost btest-opensource]# gcc -o btest *.c -lpthread
/tmp/ccL6QCDF.o: In function `test_udp_tx':
btest.c:(.text+0x1455): undefined reference to `clock_gettime'
btest.c:(.text+0x15dc): undefined reference to `clock_nanosleep'
/tmp/ccL6QCDF.o: In function `test_udp_rx':
btest.c:(.text+0x16f2): undefined reference to `clock_gettime'
/tmp/ccL6QCDF.o: In function `test_udp':
btest.c:(.text+0x1b7f): undefined reference to `clock_gettime'
btest.c:(.text+0x1bba): undefined reference to `clock_gettime'
btest.c:(.text+0x1e92): undefined reference to `clock_gettime'
/tmp/ccu5j117.o: In function `itimer_start':
timing_mach.c:(.text+0x20e): undefined reference to `clock_gettime'
/tmp/ccu5j117.o: In function `itimer_step':
timing_mach.c:(.text+0x25f): undefined reference to `clock_nanosleep'
collect2: ld returned 1 exit status

What is wrong?

Thanks

**Comment by samm-git** [comment]
compilation command is wrong. use 

```
autoreconf
./configure
make
```
